### PR TITLE
quick fix grid & individual warning before leave edition without saving

### PR DESCRIPTION
**Pull request by Matheo13**
https://www.pivotaltracker.com/story/show/145456229

### CODE REVIEW

**Comment by romfabbro** [comment]
same as https://github.com/NaturalSolutions/ecoReleve-Data/pull/561 ?

**Comment by jvitus** [comment]
problem 

Indivudals:

Edit death date in general infos, doesn't trigger the alert 

Grid Proto: 

Edit Text, Number , Select , doesn't trigger the alert

**Comment by jvitus** [comment]
Ok seems good for me 

i didn't merge just in case and wait RF review

**Comment by romfabbro** [comment]
ok

**Pull request merged**
