### PR TITLE
Réorganisation des champs du protocole Individual Equipment

### PR DESCRIPTION
**Pull request by romfabbro**
https://www.pivotaltracker.com/story/show/116879375

### CODE REVIEW

**Comment by romfabbro** [comment]
https://www.pivotaltracker.com/story/show/116879371

**Comment by ktalbi** [comment]
-> Monitoring status sur une ligne complète

**Comment by romfabbro** [comment]
you have to check PR in order, please see PR #228  before

**Comment by ktalbi** [comment]
ok

**Pull request merged**
