### PR TITLE
Blockprotodel

### PR DESCRIPTION
**Pull request by jvitus**
Empêcher la modification et la suppression de protocole individual equipment et individual unequipment et site equipment et site unequipment SI il y a des données VALIDEES qui sont associées, c'est-à-dire dans individual_locations.
"You cannot do this modification because data have already been validated with this sensor. Please contact an administrator."

https://www.pivotaltracker.com/story/show/142507465

### CODE REVIEW

**Comment by Matheo13** [comment]
Doesn't work all the time (I tried on NARC DB)

**Comment by jvitus** [comment]
yes,
The problem was in the stored procedure 

you will need to ALTER  checkIfProtoProtected .

**Comment by Matheo13** [comment]
I have a 500 on the delete of those protocols (only equipment/unequipment).

File "C:\Miniconda3\lib\site-packages\pyramid-1.7-py3.5.egg\pyramid\viewderivers.py", line 432, in viewresult_to_response
    raise ValueError(msg % (view_description(view), result))
ValueError: Could not convert return value of the view callable function ecoreleve_server.Views.error_view into a response object. The value returned was ResourceClosedError('This result object does not return rows. It has been closed automatically.',).
127.0.0.1 - - [02/May/2017 10:39:02] "DELETE /ecoReleve-Core/stations/33778272/observations/320996 HTTP/1.1" 500 8925

**Comment by romfabbro** [comment]
It could be fix now. Re Run SP script and relaunch the server

**Pull request merged**
