### PR TITLE
Proto grid edition

### PR DESCRIPTION
**Pull request by Matheo13**

### CODE REVIEW

**Comment by Matheo13** [comment]
just add {... 'grid': true ...} to root of the protocol object.
or uncomment line 102 of the lyt-protocols-editor.js the first protocol will be in grid mode.

**Comment by romfabbro** [comment]
Almost good! It could be better if user can edit multiple rows before saving and if inputs are in order with column title

**Comment by Matheo13** [comment]
I don't understand the first point.

**Comment by romfabbro** [comment]
user have to save the first row to edit another one ...

**Comment by romfabbro** [comment]
not mergeable

**Comment by romfabbro** [comment]
image

**Comment by romfabbro** [comment]
not complete, header not in the good order, 
and I can't add a new row :(. Put a button to add new row

**Comment by Matheo13** [comment]
Do not merge yet.

**Comment by Matheo13** [comment]
"uncomment line 102 of the lyt-protocols-editor.js the first protocol will be in grid mode."

Will do better later if we do better later.

**Comment by romfabbro** [comment]
ok

**Pull request merged**
