### PR TITLE
improve & Fix Export 

### PR DESCRIPTION
**Pull request by romfabbro**
New : 
- add session pool for DB_Export, you have to add in config file (development.ini) these rows:
  sqlalchemy.Export.url = DRIVER={SQL Server};Server=.\SQLSERVER2008;Database=yourDB_exportName;UID=Login;PWD=password;Trusted_Connection=Yes
  sqlalchemy.Export.implicit_returning = False
  sqlalchemy.Export.pool_reset_on_return = commit
  sqlalchemy.Export.pool_size = 30
  sqlalchemy.Export.pool_timeout = 5
  sqlalchemy.Export.max_overflow = 10
  sqlalchemy.Export.case_sensitive= False
- some fixes in filter export 
- some fixes and improvements  in export files
- add new final message for export process

### CODE REVIEW

**Comment by orovellotti** [comment]
Would be good to have a description

**Comment by orovellotti** [comment]
The Pr seems very big

**Comment by romfabbro** [comment]
ok, seen with mateo

**Comment by Matheo13** [comment]
remplace sqlalchemy.url by sqlalchemy.default.url
& remove Trusted_Connection=Yes

**Pull request merged**
