### PR TITLE
BACK: add camera trap in equipment history

### PR DESCRIPTION
**Pull request by romfabbro**
https://www.pivotaltracker.com/story/show/147045279

### CODE REVIEW

**Comment by jvitus** [comment]
Seems ok when i read the code 

but got error on front 
(when open sensors page)
image

(when click on Deployment )

image

**Comment by romfabbro** [comment]
it is existing bugs, independant of this PR. please create an issue to fix its

**Comment by romfabbro** [comment]
1st error : because there is no position for sensor (because the map is useless for this functionnality) 
the 2nd existing since ag grid was implemented in deails view

**Comment by jvitus** [comment]
#592 Create issue for front bug

Ok so it's good for me
we can merge it

**Pull request merged**
