### PR TITLE
Transect

### PR DESCRIPTION
**Pull request by romfabbro**
https://www.pivotaltracker.com/story/show/119520641

### CODE REVIEW

**Comment by FredericBerton** [comment]
It was possible to create transect protocol.
What should I do for "Gestion du stockage en propriété dynamiques."?
Unable to test data migration

**Comment by FredericBerton** [comment]
Is it normal to be able to save the protocol with mpty lines in the grid ?

**Comment by FredericBerton** [comment]
Migration is ok with the new pipe.

**Comment by romfabbro** [comment]
set taxon required in subfrom transect

**Pull request merged**
