### PR TITLE
Release aggrid: add error on sensor duplicate & sensor not available

### PR DESCRIPTION
**Pull request by romfabbro**
https://www.pivotaltracker.com/story/show/132647127

### CODE REVIEW

**Comment by Matheo13** [comment]
image

**Comment by Matheo13** [comment]
Due to base? I don't understand all your code, for instance, why do you need a cellRenderer? It isn't used in my case.

**Comment by romfabbro** [comment]
please stop to push everything on my branch :
	improve filters			2f8f7cb
 @Matheo13	revert modif/tests on form			b5ddaae
 @jvitus	Merge pull request #362 from Matheo13/handle_select_unselected_checkbox …			029194a
 @Matheo13	Merge branch 'development' of https://github.com/NaturalSolutions/eco…  …			39dc7f6
 @Matheo13	bla			4d610c3
 @Matheo13	Merge pull request #364 from Matheo13/ui_filters  …			42be806
 @ktalbi	quick fix			62a1bf6
 @ktalbi	Merge branch 'development' of https://github.com/NaturalSolutions/eco…  …			ae52288
 @ktalbi	fix demo import gpx			5754344
 @Matheo13	Merge pull request #366 from ktalbi/demo_fix  …			da16cb3
 @Matheo13	revue

To check a PR, please refer you to the google doc in Ns/googledrive thank you

**Comment by romfabbro** [comment]
I need a cellRenderer because I need the objectPicker return an object{label,value} and I need to display  the label only

**Comment by Matheo13** [comment]
No I won't stop to push every thing on your branch when I need to work on it and when your branch isn't up to date and there is a conflict.

Regarding google doc you know whath? Omg, I didn't know there was such a document like this!
Sure you shared me an invitation 3 month ago without any explanations, and I guess I was in hollydays.
Then a bad emoji when I ask a question, revue how you communicate, it's not aprreciated.

Good we.

**Comment by romfabbro** [comment]
you are wrong

**Comment by romfabbro** [comment]
CellRender is called, AND I Need it because I don't find another way to stored a value and to display another one (label)

**Comment by Matheo13** [comment]
Yes I'm wrong about last point, I talk too fast, guess why.
Anyway It's due to the database, I don't have uncIdentifier in my base but sensorName or somthing like that I forgot, that's why the cellRenderer isn't used in my case.

**Comment by romfabbro** [comment]
No problem, if you think I can do better, show me in the code. I tried to use ValueFormatter and another aggrid method to get a different value of the displayed value but I didn't find another way.

**Comment by Matheo13** [comment]
Rdy?

**Comment by romfabbro** [comment]
yes

**Comment by romfabbro** [comment]
ok

**Pull request merged**
