### PR TITLE
ag-grid

### PR DESCRIPTION
**Pull request by Matheo13**

### CODE REVIEW

**Comment by Matheo13** [comment]
Basic design for the moment.

**Comment by romfabbro** [comment]
super

**Comment by Matheo13** [comment]
previous commit: better than nothing for the moment.

**Comment by romfabbro** [comment]
nice, don't forget the "select All" checkbox for the validate and gpx grid

**Comment by Matheo13** [comment]
I'll have to implement it, there isn't any by default on ag-grid

**Comment by Matheo13** [comment]
need dependance update
`npm install`
`bower install`

**Comment by Matheo13** [comment]
I invite you to remove your bower_components & node_modules folders then,
`bower cache clean`
`bower install`

`npm cache clean`
`npm install`

**Comment by romfabbro** [comment]
**\* TODO  in import GPX : 
- quick fix drag n drop file (enable "Next" when drop) 
- fix date format in grid step2 (convert unix timeStamp into date format dd/mm/YYYY HH:MM:SS) (done)

**Comment by romfabbro** [comment]
- fix date format in grid step2 (convert unix timeStamp into date format dd/mm/YYYY HH:MM:SS) (done)

**Comment by romfabbro** [comment]
youpiiiiiii

**Pull request merged**
