### PR TITLE
Security role + ajaxPool refact

### PR DESCRIPTION
**Pull request by romfabbro**
https://www.pivotaltracker.com/story/show/119515667

https://www.pivotaltracker.com/story/show/122451621

https://www.pivotaltracker.com/story/show/122456871

You have to set master_secret for cookie decoding in development.ini , add this row : 
jwtauth.master_secret = yoursecret

### CODE REVIEW

**Comment by FredericBerton** [comment]
https://www.pivotaltracker.com/story/show/122451621

https://www.pivotaltracker.com/story/show/122456871

**Comment by romfabbro** [comment]
done

**Comment by FredericBerton** [comment]
-user can access to release section
-user can access and validate ARGOS and GSM things
-user can access to manual import of GSM things

**Comment by romfabbro** [comment]
waiting for front implementation

**Comment by romfabbro** [comment]
it's ok for me, just fix conflict please and re-active user class from header

**Comment by Matheo13** [comment]
To re-test.

**Comment by FredericBerton** [comment]
In administrator mode :

# for station
- when I click on "supprimer" and if I choose "Yes, delete it !", nothing happen
- in edit mode no field can be edited
- "nettoyer" seems to clean only the field "region"
- when I click "enregistrer" nothing happen and everything stay in edit mode

# for Monitored Sites
- when I click on "supprimer" and if I choose "Yes, delete it !", nothing happen

# for Sensors
- when I click on "supprimer" and if I choose "Yes, delete it !", nothing happen

#for my data
-it is not clickable

**Comment by FredericBerton** [comment]
In super user mode 

# for individuals
- after creating a new individual if you choose create another, all the fields are already complete with the value of the previous entry. We should clean the form don't we ?
- i was able to create a new individual

# for monitored sites
- impossible to save after edit

# for release

-Why to display the button "use to release" if you don't have permission to use it ?

#for export
-in the display I have nothing
capture

#for my data
-it is not clickable

**Comment by FredericBerton** [comment]
In user mode 

# for monitored sites
- impossible to save after edit

# for release

-Why to display the button "use to release" if you don't have permission to use it ?

#for export
-in the display I have nothing
capture

#for my data
-it is not clickable

**Comment by FredericBerton** [comment]
Should I try to test with forbidden rights or we assume that the portal do th ejob to leave or not access at the application ?

**Comment by FredericBerton** [comment]
In administrator mode :

# for Monitored Sites
- when I click on "supprimer" and if I choose "Yes, delete it !", nothing happen

# for Sensors
- when I click on "supprimer" and if I choose "Yes, delete it !", nothing happen

**Comment by FredericBerton** [comment]
In Super User mode :

# for monitored sites
- impossible to save after edit

# for release

-i have an empty grid
-Why to display the button "use to release" if you don't have permission to use it ?

**Comment by FredericBerton** [comment]
In User mode

# for monitored sites
- impossible to save after edit

# for release

-Why to display the button "use to release" if you don't have permission to use it ?

**Comment by romfabbro** [comment]
see PR https://github.com/NaturalSolutions/ecoReleve-Data/pull/318

**Comment by FredericBerton** [comment]
In User mode

# for monitored sites
- impossible to save after edit

# for release

-Why to display the button "use to release" if you don't have permission to use it ?

**Pull request merged**
