### PR TITLE
ADD | indiv , positions filter

### PR DESCRIPTION
**Pull request by ktalbi**

### CODE REVIEW

**Comment by romfabbro** [comment]
Can you remove ID column from individual location table, 
Change CSS (margin-bottom) under filter,
AND Commit your changes in NaturalJSFilter,
please

**Comment by ktalbi** [comment]
done

**Comment by romfabbro** [comment]
good, 
Can you make a select input  for FiledActivity (load fieldActivity list in)

**Comment by ktalbi** [comment]
ok

**Comment by romfabbro** [comment]
problem with map when we move on the next individual. Map is not destroy and keep the previous locations

**Comment by romfabbro** [comment]
fix confilcts please, keep MonitoredSiteList class in Model/List.py

**Comment by romfabbro** [comment]
refresh map is fixed, but interaction filter/grid and map is broken when I move on the next or prev individual

**Comment by Matheo13** [comment]
Ok, I'll try when conflicts are resloved.

**Comment by romfabbro** [comment]
ok

**Pull request merged**
