### PR TITLE
Back refact v2

### PR DESCRIPTION
**Pull request by romfabbro**

### CODE REVIEW

**Comment by ktalbi** [comment]
bug, new station : KeyError (FK_StationType)
new obs : FK_ProtocoleType
thesaurus val for monitored sites
export don't work (example : plant inventory ) ecoReleveCore/export/views/25/?geo=true  --> geojson =null

**Comment by ktalbi** [comment]
ok for creation (station, obs) . Thesaurus don't work 1 time /2

**Comment by romfabbro** [comment]
you need to open an new 
issue for the thesaurus loading problems

**Comment by ktalbi** [comment]
ok

**Comment by Matheo13** [comment]
I know I'm not an example and it's often hard to do, but we should try to make lighter pull request and to split it.
It's hard to review otherwise.

**Comment by romfabbro** [comment]
it's a refact and I can't do a shorter pull request and it isn't a big PR. If you really look the code just 2 files have been changed, other changes affect variable or method renaming...

**Pull request merged**
