### PR TITLE
Row index & thesaurus refact

### PR DESCRIPTION
**Pull request by Matheo13**
tell me if that fits.

### CODE REVIEW

**Comment by Matheo13** [comment]
squash or rebase on merge plz.

**Comment by romfabbro** [comment]
auto incrementation/decrementation works fine, but some issues still remain:

- [x] In a sugGridForm : when I have deleted a row I can't save the protocol (error: Uncaught TypeError: Cannot read property 'fieldClass' of undefined)  **---> sorry is fixed**

- [x] In a sugGridForm (VertebrateGroup) : when I have entered a wrong Individual ID in a subgrid row , an error appear in the cell, but I can still save the form and it's saving with no data attached for the subgrid.

Can you fix that in this Pull Request (it's an existing bug in development branch) ? Or In another one as you want

**Comment by romfabbro** [comment]
ok

**Comment by romfabbro** [comment]
it's good for me, test my new commit and you can merge

**Comment by Matheo13** [comment]
Ok

**Pull request merged**
