### PR TITLE
Map improvments

### PR DESCRIPTION
**Pull request by Matheo13**

### CODE REVIEW

**Comment by romfabbro** [comment]
I can't see any changes. The legend display is good but locations on map are not displayed as the legend

**Comment by Matheo13** [comment]
grunt less? But if you have the legend you already made it.

You should be able to see the difference in the individual detail view no?
For others, the "type_" is missing in the feature geojson object.

**Comment by romfabbro** [comment]
grunt less / jst / dev are done

**Comment by romfabbro** [comment]
image

**Comment by romfabbro** [comment]
image

**Comment by Matheo13** [comment]
type_ : arg -> argos

**Comment by romfabbro** [comment]
ok

**Pull request merged**
