### PR TITLE
Grid forms

### PR DESCRIPTION
**Pull request by Matheo13**
First version of the sub forms in ag-grid mod.
_Sorry for the commit names._

### CODE REVIEW

**Comment by Matheo13** [comment]
missing menu interactions (& others features)

**Comment by Matheo13** [comment]
changed: enable/disable : protocols.view.js line 69

**Comment by Matheo13** [comment]
known bugs: 
- thesaurus picker it-self.
- autocomplete: first call isn't made.
--> both: still the same question, should we avoid first call and get right data directly from the server?
- dateTimePicker: waiting for JV & VB fix. OK

**Comment by Matheo13** [comment]
Todo
- [x] swal on error
- [ ] define focus bhv
- [ ] define add row bhv (disable? menu icon)

**Comment by Matheo13** [comment]
not sure about last commit, still dirty
waiting for Tom's updates about thesaurus errors

**Comment by jvitus** [comment]
Problem on bird biometry protocol 

observer and assistant first id is renderer
if we edit , we get the name.

Need back send
 { 'value' : 'id',
'label' : 'name' } 

Pb on sensors :
id is displayed we expect unicidentifier

When we save if we get error 500 from back no error is displayed to inform user

We can insert empty row

**Comment by jvitus** [comment]
Bug on proto release group col release individual 

bug proto release groupe field release individual

Same on vertebrate group col vertebrate individual


MJ: sub protocols are already grids

**Comment by jvitus** [comment]
Checkbox UI pb 

we need to have focus on the cell before click on checkbox 
that's could be more user friendly if on cell click we check/unchecked

MJ: to define

**Comment by jvitus** [comment]
when edit that's could be cool if col width fit to cell values then go back to original width on leave
or a tooltip when hover

MJ: to define

**Comment by jvitus** [comment]
protocol capture group last col is an empty col 
capture group empty col

MJ: sub protocols are already grids

**Comment by romfabbro** [comment]
to pass Observation as Grid set the Status in ProtocolType table to 10
if you want test all Observation as Grid uncomment line 69 from protocols.view.js

**Comment by Matheo13** [comment]
not sure about autocomplete bhv

**Comment by Matheo13** [comment]
Normally the validation would work for both client and back sides.
**It must be tested carefully.**

Waiting for autocomplete changes regarding observer && assistant.

Object picker aren't optimized yet I think. Must be refacted.

**Comment by Matheo13** [comment]
A new empty line is added if editing the last one.
Save function doesn't care about empty lines.
A new line isn't an any more an empty line once you started to edit it.

**Comment by Matheo13** [comment]
So?

**Pull request merged**
