### PR TITLE
API refactoring

### PR DESCRIPTION
**Pull request by romfabbro**

### CODE REVIEW

**Comment by romfabbro** [comment]
TODO:

- [ ] add security

- [ ]  Release View 

- [ ]  Sensor data view

**Comment by Matheo13** [comment]
url traversal seems a lot better!
I take a look on it

**Comment by romfabbro** [comment]
security issue ("Unauthorized") on object creation is fixed

**Comment by romfabbro** [comment]
TODO:

- [x] observation view

- [x] security

- [x]  Release View 

- [x] Export view
- [x]  autocomplete view
- [x]  autocomplete config SQL need to be refact as {object}/autocomplete/... instead of autocomplete/{object}/... (meanwhile old autocomplete route is working )
- [x]  Sensor data view


- [x]  Fix check Individual code (not due to refact ==> bad SQL query)



- [x]  security/login view

- [x] user view

**Comment by romfabbro** [comment]
it can be merged

**Comment by Matheo13** [comment]
Ok I check

**Comment by romfabbro** [comment]
TODO (maybe in another PR):

- [ ]  autocomplete config SQL need to be refact as {object}/autocomplete/... instead of autocomplete/{object}/... (meanwhile old autocomplete route is working ) then remove url dispatch

- [ ]  Sensor data view

- [ ]  Fix check Individual code (not due to refact ==> bad SQL query)

- [ ]  security/login view

- [ ] user view

**Comment by Matheo13** [comment]
Ok

**Comment by Matheo13** [comment]
Ok

**Pull request merged**
