### PR TITLE
handle thesuaurs default values

### PR DESCRIPTION
**Pull request by Matheo13**
https://www.pivotaltracker.com/story/show/146177809

### CODE REVIEW

**Comment by jvitus** [comment]
some pb 
when i open 
http://localhost/ecoreleve/#stations/1591?proto=218&obs=376111 (narc database)

image

nothing on sensor status

when i click on edit 

image

**Comment by romfabbro** [comment]
it would be fix back side, better and faster

**Comment by romfabbro** [comment]
https://github.com/NaturalSolutions/ecoReleve-Data/pull/550

**Comment by Matheo13** [comment]
no... really?

**Pull request closed without merging**
