### PR TITLE
Kt branch

### PR DESCRIPTION
**Pull request by ktalbi**
to test traduction, you need to add a key to config.js:
language : 'fr'

### CODE REVIEW

**Comment by romfabbro** [comment]
Your branch is not mergeable, please pull the NS/master and fix conflicts

**Comment by romfabbro** [comment]
ok

**Comment by ktalbi** [comment]
Yes, you nedd it  to load local json files (traduction files).
'en' is default language, if you like to test 'fr', you add  a property:
'language' : 'fr'         in config.js

**Comment by romfabbro** [comment]
ok

**Pull request merged**
