### PR TITLE
Subform

### PR DESCRIPTION
**Pull request by jvitus**
now we can deleted any subform, if we deleted the last one an empty is created to replace it

https://www.pivotaltracker.com/story/show/132647899

total number of subform implemented
each subform identify with his number

https://www.pivotaltracker.com/story/show/132647883

### CODE REVIEW

**Comment by romfabbro** [comment]
petit bug sur le badge, il n'apparaît que quand on ajoute un subform
image

**Comment by romfabbro** [comment]
après avoir ajouté un subform
image

**Comment by romfabbro** [comment]
can you review this conflict and fix the bug?

**Comment by jvitus** [comment]
subform

bug and conflicts fixed
style num subform changed

**Comment by romfabbro** [comment]
ok

**Pull request merged**
