### PR TITLE
form : Prohibit negative numbers

### PR DESCRIPTION
**Pull request by ktalbi**
137011661

### CODE REVIEW

**Comment by Matheo13** [comment]
Use HTML5 min max properties.

I did here for instance in object picker https://github.com/Matheo13/ecoReleve-Data/blob/a11c1c4aa6f523a658e1efd43e184cebe6293a3b/Front/app/ns_modules/ns_bbfe/bbfe-objectPicker/tpl-bbfe-objectPicker.html.

Lat/lon has to be between 180 and -180
Object picker > 0
I don't know if there are other exceptions.

**Comment by romfabbro** [comment]
min/max HTML attributes are not enough. If you use only these attributes you can save the form

**Comment by Matheo13** [comment]
I saw, that's borring.

**Comment by Matheo13** [comment]
Ok

**Pull request merged**
